name: Releasing Objects

on: [push]

jobs:
  compile:
    name: Compile .o files and release them
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Choco install MinGW
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install mingw --version 9.4.0 --force

      - name: Configure CMake
        run: cmake -G "MinGW Makefiles" ${{github.workspace}}

      - name: Build .obj and zip
        run: |
          cmake --build .
          echo "COUCOU"
          Get-ChildItem -Path .
          Get-ChildItem -Path CMakeFiles

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./libReference.a
          asset_name: libReference.a
          tag: latest
          overwrite: true
          body: "Latest Reference.lib for reference-obj"
