name: Releasing Objects

on: [push]

jobs:
  compile:
    name: Compile .o files and release them
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create temporary folder
        run: mkdir zip

      - name: Configure CMake
        run: cmake ${{github.workspace}}

      - name: Build .obj and zip
        run: |
          cmake --build .
          echo "COUCOU"
          Get-ChildItem -Path .
          Get-ChildItem -Path CMakeFiles
          Get-ChildItem -Path Reference.dir
          Get-ChildItem -Path Debug
          Get-ChildItem -Path x64
          Get-ChildItem -Path _deps

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.tag }}
#          draft: false
#          prerelease: false
#
      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Debug/Reference.Lib
          asset_name: Reference.lib
          tag: latest
          overwrite: true
          body: "Latest Reference.lib for reference-obj"
